services:
  redis:
    image: redis:7-alpine
    container_name: posso-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: posso-app-dev
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - RUN_MODE=web
      - DEV_MODE=true  # Enable auto-reload
    volumes:
      - .:/app  # Mount entire project for hot reload
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    command: python main.py

volumes:
  redis_dev_data: